//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.20 at 06:26:12 PM CET 
//


package net.andruszko.lepapp.web.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * zadanie
 * 
 * <p>Java class for lepItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lepItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="question" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subSectionId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="answer_a" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answer_b" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answer_c" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answer_d" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="answer_e" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="correct_ans">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="A"/>
 *               &lt;enumeration value="B"/>
 *               &lt;enumeration value="C"/>
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="E"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lepItem", propOrder = {
    "id",
    "position",
    "question",
    "subSectionId",
    "answerA",
    "answerB",
    "answerC",
    "answerD",
    "answerE",
    "correctAns"
})
public class LepItem {

    protected long id;
    protected int position;
    @XmlElement(required = true)
    protected String question;
    protected long subSectionId;
    @XmlElement(name = "answer_a", required = true)
    protected String answerA;
    @XmlElement(name = "answer_b", required = true)
    protected String answerB;
    @XmlElement(name = "answer_c", required = true)
    protected String answerC;
    @XmlElement(name = "answer_d", required = true)
    protected String answerD;
    @XmlElement(name = "answer_e", required = true)
    protected String answerE;
    @XmlElement(name = "correct_ans", required = true)
    protected String correctAns;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

    /**
     * Gets the value of the question property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestion() {
        return question;
    }

    /**
     * Sets the value of the question property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestion(String value) {
        this.question = value;
    }

    /**
     * Gets the value of the subSectionId property.
     * 
     */
    public long getSubSectionId() {
        return subSectionId;
    }

    /**
     * Sets the value of the subSectionId property.
     * 
     */
    public void setSubSectionId(long value) {
        this.subSectionId = value;
    }

    /**
     * Gets the value of the answerA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerA() {
        return answerA;
    }

    /**
     * Sets the value of the answerA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerA(String value) {
        this.answerA = value;
    }

    /**
     * Gets the value of the answerB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerB() {
        return answerB;
    }

    /**
     * Sets the value of the answerB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerB(String value) {
        this.answerB = value;
    }

    /**
     * Gets the value of the answerC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerC() {
        return answerC;
    }

    /**
     * Sets the value of the answerC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerC(String value) {
        this.answerC = value;
    }

    /**
     * Gets the value of the answerD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerD() {
        return answerD;
    }

    /**
     * Sets the value of the answerD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerD(String value) {
        this.answerD = value;
    }

    /**
     * Gets the value of the answerE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerE() {
        return answerE;
    }

    /**
     * Sets the value of the answerE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerE(String value) {
        this.answerE = value;
    }

    /**
     * Gets the value of the correctAns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectAns() {
        return correctAns;
    }

    /**
     * Sets the value of the correctAns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectAns(String value) {
        this.correctAns = value;
    }

}
