//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 09:06:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "net.andruszko.lepapp.web")
package net.andruszko.lepapp.web.vo;
